### ISSUE TITLE
Add Cypress test to draggable only

### ISSUE THREAD

**Issue by jalal246** [jalal246/dflex#125]
- [x] Initiate test. AddingCypress to Draggable (#188)
- [ ] Add test cases including 
     - [ ]  Horizontal movement
     - [ ] Vertical movement

**Comment by Pranay0302** [comment]
hey @jalal246, i would like to work on this issue.

**Comment by jalal246** [comment]
@Pranay0302 Awesome. Let me know if there's something I can do to make things easier. Maybe discord if you want to.

**Comment by Pranay0302** [comment]
Sure! 
Give me your discord tag for further discussions if necessary

**Comment by jalal246** [comment]
@Pranay0302 It's `jalal#9038`
