### ISSUE TITLE
Add Vue template for DnD 

### ISSUE THREAD

**Issue by jalal246** [jalal246/dflex#69]
This issue is dedicated to creating a template for the Vue framework.

I used create-react-app to create react [playgrounds](https://github.com/jalal246/dflex/tree/master/playgrounds) which I usually use to develop DFlex. But looking to publish a template for Vue, something like this repo: [https://github.com/dflex-js/react-draggable-starter](https://github.com/dflex-js/react-draggable-starter).

For the sake of productivity, creating a [starter](https://github.com/dflex-js/vue-dnd-starter) form scratch can be simpler than open PR directly to this rep. Both, of course, are welcomed 🎉🎉🎉

**Comment by jalal246** [comment]
This is a related issue here #36

**Comment by jalal246** [comment]
Hey @nagwan. Are you still interested?

**Comment by nagwan** [comment]
@jalal246 hi jalal, sure i am, 
i won`t be able to start figuring out things this week, 
if this suits u i may start next week

**Comment by Tepexic** [comment]
Hi,
I put together [this example Vue app](https://github.com/Tepexic/vue-dnd-starter) that could work as a fix for this issue.  I would have made a PR, but it seems that I can't clone the starter.

**Comment by jalal246** [comment]
@Tepexic  Thank you, Jesús! I am thinking about adding `Vue` to the main repo, here. Do you want to make PR?
Would be nice if there's a `dflex-vue-dnd` in [playground] (https://github.com/jalal246/dflex/tree/master/packages/dnd/playgrounds) along with `React`.

And then, importing `dnd` immediately form source. So in `container.js`,  using `@dflex/dnd/src` instead of using `@dflex/draggable`.  The same in `core.js` > `@dflex/dnd/src`.

If you want to make changes in CSS or even build only one list, that's would be fine. If you face any problem using `yarn` we can solve this out. Just let me know.

**Comment by Tepexic** [comment]
Sounds good, I'll get to it then, thanks!

**Comment by jalal246** [comment]
Fixed with #102, #106. Thanks to @Tepexic

**Comment by jalal246** [comment]
Hey @Tepexic. Are you interested in #36? Or any other contribution? 😄

**Comment by Tepexic** [comment]
Sure! I was actually trying to close both with the same PR, but I ran into some issues with the DnD playground. I'll circle back and see what I did wrong.

**Comment by jalal246** [comment]
that's because the package itself is buggy 😆 but still need more cases other than react 🥳
