### ISSUE TITLE
Defining drop zone

### ISSUE THREAD

**Issue by sibbngheid** [jalal246/dflex#71]
Defining where elements can be dropped would be awesome.

**Comment by jalal246** [comment]
Yes, I think this is a good feature. Giving each element the ability to be draggable, droppable, or both.  

For draggable you have the ability to control it with a mouse event handler. While for droppable it can be done through a registration.

Something like this:

`store.register({ id, element, isDroppable})`

**Comment by ddenev** [comment]
@jalal246, I see the stale bot closes a lot of actually unresolved requests. would it be possible to stop it from doing it as it is misleading us to think issues/requests are resolved while they are not :)

+1 to the drop zone feature request.

**Comment by jalal246** [comment]
@ddenev You can define it by passing `readonly :true` to exclude an element from being drop zone.

```
  React.useEffect(() => {
  // This element will be fixed during drag and drop.
   store.register({ id: "my-id", readonly: true });
    return () => {
      store.unregister(id);
    };
  }, []);
  ```
